### ISSUE TITLE
Add "Big Data/ Data Science/ Analytics " tag line in pycon website

### ISSUE THREAD

**Issue by railsstudent** [404busters/pyconhk-2017#42]
Put "Big Data/ Data Science/ Analytics" between date and logo

![selection_001](https://user-images.githubusercontent.com/1159649/30775583-22e63fb4-a0c9-11e7-950c-2c0c276ac9bb.png)

**Comment by tonyhhyip** [comment]
@railsstudent The photos is HKOSCon...

**Comment by railsstudent** [comment]
right. Brain dead

**Comment by yookoala** [comment]
@railsstudent take it easy.

**Comment by railsstudent** [comment]
Fixed by #52
