### ISSUE TITLE
Console error when calling l firebase database

### ISSUE THREAD

**Issue by railsstudent** [404busters/pyconhk-2017#43]
![selection_002](https://user-images.githubusercontent.com/1159649/30775619-763186fa-a0ca-11e7-8d97-f8ede5f4955a.png)

**Comment by railsstudent** [comment]
![22014840_527250027617467_269312123_n](https://user-images.githubusercontent.com/1159649/30775905-66e9a182-a0cf-11e7-8f65-06781ed1cc2a.png)

Report by speaker

**Comment by railsstudent** [comment]
Remove all firebase call

**Comment by yookoala** [comment]
I think the "database_name" variable is not set properly here.

**Comment by railsstudent** [comment]
@yookoala  I don't even know if firebase is configured for pyconhk 2017

**Comment by yookoala** [comment]
Me neither. XD

We'll consult with out Firebase expert (Tony) :-)
