### ISSUE TITLE
Update og image in site.yml file

### ISSUE THREAD

**Issue by railsstudent** [404busters/pyconhk-2017#45]
Question: Where should the image be hosted?  Locally or in file server?

**Comment by tonyhhyip** [comment]
Directly put it in the git repo

**Comment by railsstudent** [comment]
i did.
it does not show in preview.
http://pycon.hk/2017/images/og/2017.png exists but not not shown in Open Graph debugger tool

**Comment by yookoala** [comment]
![2017-10-25 20-41-38](https://user-images.githubusercontent.com/91274/31999207-153add56-b9c5-11e7-9b34-cbb92998ef3c.png)
