### ISSUE TITLE
Add sponsor logos to front page 

### ISSUE THREAD

**Issue by railsstudent** [404busters/pyconhk-2017#66]
Silver sponsor and general sponsors in the first row
Venue sponsor in the second row

Please use pycon.hk/2016/  as reference
<img width="1096" alt="screen shot 2017-10-25 at 1 08 28 pm" src="https://user-images.githubusercontent.com/1159649/31981480-23b41292-b986-11e7-9131-e739bce1fe6f.png">

**Comment by 199911** [comment]
Silver Sponsor: 
- Python Software Foundation
  - https://file.pycon.hk/2017/logos/psf.png
  - https://www.python.org/psf/

General Sponsor:
- Alvanon
  - https://file.pycon.hk/2017/logos/alvanon.png
  - http://alvanon.com/
- MySQL
  - http://img.opensource.hk/logo-mysql-500.jpg
  - https://www.mysql.com/
- (To Be Confirmed) AXA-IM (edited)

Venue sponsor:
- City University of Hong Kong
  - https://file.pycon.hk/2017/logos/CityU_Logo_Standard_Signature.png
- CityU Apps Lab
  - https://file.pycon.hk/2017/logos/main_logo.png

**Comment by 199911** [comment]
@tonyhhyip plz help

**Comment by 199911** [comment]
After discuss, will remove venue sponsor

**Comment by railsstudent** [comment]
Fixed by #70
